<?php
    $api_key="rzp_test_y2kVZIco1FJDTE";
    session_start();
?>
<form action="" method="POST">
<script
    src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="<?php echo $api_key; ?>" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="<?php echo $_SESSION['room']['payment']*100; ?>" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-id="<?php 'ORD_'.$SESSION['user_id'].random_int(11111,9999999);?>"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Floris31 Resort"
    data-description="Payment system"
    data-image="images/Rooms/logo-removebg-preview.png"
    data-prefill.name="<?php echo $_SESSION['username']; ?>"
    data-prefill.email=""
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
